name: Pull Request Cleanup
on:
  pull_request:
    types: [closed]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_role_name: webinvest-pipeline_cd-nonprod
  TF_VAR_account_id: '069537940840'
  TF_VAR_team_github_token: ${{ secrets.TEAM_GITHUB_TOKEN }}
  TF_VAR_teams_webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
  PR_NUMBER: ${{ github.event.number }}
  REPO_NAME: ${{ github.event.repository.name }}
  REACT_APP_STAGE: development
#concurrency: queue-${{ github.ref }} # Queue builds per git ref. concurrent updates to terraform cause errors.

jobs:
  # The website distribution remains in S3 for log purposes
  infra-pull-request:
    name: Delete Pull Request Alias
    runs-on: ubuntu-latest
    environment: nonprod

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - uses: terraform-compliance/github_action@main
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.0.0
      - uses: fusion-engineering/setup-git-credentials@v2.0.6
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::${{ env.TF_VAR_account_id }}:role/${{ env.TF_VAR_role_name }}
          role-duration-seconds: 1200

      - name: Remove PR folder
        run: |
          aws s3 rm --recursive s3://webinvest-nonprod-${{ env.TF_VAR_account_id }}/${{ env.REPO_NAME }}/v/${{ env.PR_NUMBER }}
