# Validates the semantic release title for PRs
# https://github.com/marketplace/actions/semantic-pull-request
name: 'Semantic Release PR title'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, converted_to_draft, ready_for_review]
jobs:
  main:
    name: Validate Semantic Release PR title
    runs-on: ubuntu-20.04
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TEAM_PAT }}
